# .air.toml

# Define the directories to watch for changes.
[build]
watch = [
    "./cmd",
    "./pkg"
]
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]
cmd = "go build -o ./tmp/main ./cmd/main/main.go"

# Define the entry point of your application.
[run]
command = "go"
args = ["run", "cmd/main/main.go"]
